language: python
python:
  - "3.8"
before_install:
  - pip install -U pip
  - - pip install -U pytest
  - pip install codecov
install:
  - pip install -U .
script:
  - pytest
after_success:
  - codecov
